name: Continuous Integration
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run check

  integration_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        measure: [EXM104, EXM105, EXM124, EXM125, EXM130, EXM506]
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}  
    - run: npm ci
    - run: sudo chmod +x ./src/_tests_/setup.sh
    - run: ./src/_tests_/setup.sh
    - run: sudo chmod +x ./src/_tests_/test_measures.sh
    - run: ./src/_tests_/test_measures.sh ${{ matrix.measure }}
