/*
The PatientParameters object is the result of parsing the Patient Compartment Definition and gathering the
search parameters for each resource.*

The script for parsing the Patient Compartment Definition can be found in projjecttacoma/deqm-test-server.

Patient Compartment Definition JSON: https://build.fhir.org/compartmentdefinition-patient.json.html
Patient Compartment Definition parsing script: https://github.com/projecttacoma/deqm-test-server/blob/main/src/scripts/parseCompartmentDefinition.js
 */
export const PatientParameters = {
  Account: ['subject'],
  AdverseEvent: ['subject'],
  AllergyIntolerance: ['patient', 'recorder', 'asserter'],
  Appointment: ['actor'],
  AppointmentResponse: ['actor'],
  AuditEvent: ['patient'],
  Basic: ['patient', 'author'],
  BodyStructure: ['patient'],
  CarePlan: ['patient', 'performer'],
  CareTeam: ['patient', 'participant'],
  ChargeItem: ['subject'],
  Claim: ['patient', 'payee'],
  ClaimResponse: ['patient'],
  ClinicalImpression: ['subject'],
  Communication: ['subject', 'sender', 'recipient'],
  CommunicationRequest: ['subject', 'sender', 'recipient', 'requester'],
  Composition: ['subject', 'author', 'attester'],
  Condition: ['patient', 'asserter'],
  Consent: ['patient'],
  Coverage: ['policy-holder', 'subscriber', 'beneficiary', 'payor'],
  CoverageEligibilityRequest: ['patient'],
  CoverageEligibilityResponse: ['patient'],
  DetectedIssue: ['patient'],
  DeviceRequest: ['subject', 'performer'],
  DeviceUseStatement: ['subject'],
  DiagnosticReport: ['subject'],
  DocumentManifest: ['subject', 'author', 'recipient'],
  DocumentReference: ['subject', 'author'],
  Encounter: ['patient'],
  EnrollmentRequest: ['subject'],
  EpisodeOfCare: ['patient'],
  ExplanationOfBenefit: ['patient', 'payee'],
  FamilyMemberHistory: ['patient'],
  Flag: ['patient'],
  Goal: ['patient'],
  Group: ['member'],
  ImagingStudy: ['patient'],
  Immunization: ['patient'],
  ImmunizationEvaluation: ['patient'],
  ImmunizationRecommendation: ['patient'],
  Invoice: ['subject', 'patient', 'recipient'],
  List: ['subject', 'source'],
  MeasureReport: ['patient'],
  Media: ['subject'],
  MedicationAdministration: ['patient', 'performer', 'subject'],
  MedicationDispense: ['subject', 'patient', 'receiver'],
  MedicationRequest: ['subject'],
  MedicationStatement: ['subject'],
  MolecularSequence: ['patient'],
  NutritionOrder: ['patient'],
  Observation: ['subject', 'performer'],
  Patient: ['link'],
  Person: ['patient'],
  Procedure: ['patient', 'performer'],
  Provenance: ['patient'],
  QuestionnaireResponse: ['subject', 'author'],
  RelatedPerson: ['patient'],
  RequestGroup: ['subject', 'participant'],
  ResearchSubject: ['individual'],
  RiskAssessment: ['subject'],
  Schedule: ['actor'],
  ServiceRequest: ['subject', 'performer'],
  Specimen: ['subject'],
  SupplyDelivery: ['patient'],
  SupplyRequest: ['subject'],
  VisionPrescription: ['patient']
};
